# This workflow will build a Java project with Gradle and push a new docker image to docker hub
name: Build and Push Image to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build with Gradle and Push
        run: ./gradlew jib
